import Navbar from '@/components/Navbar'
import { AppDataProvider } from './context/Appdata'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <AppDataProvider>
        {children}
        </AppDataProvider>
        <Footer/>
        </body>
    </html>
  )
}
